const ESTABLISH_CONNECTION = 'ESTABLISH_CONNECTION';

const ADD_MESSAGES = 'ADD_MESSAGES';
const SEND_MESSAGE = 'SEND_MESSAGE';

const SAVE_USERNAME = 'SAVE_USERNAME';
const LOAD_USERNAME = 'LOAD_USERNAME';
const SET_USERNAME = 'SET_USERNAME';

const LS_SET = 'LS:SET';
const LS_GET = 'LS:GET';
const LS_CLEAR = 'LS:CLEAR';

const WS_CONNECT = 'WS:CONNECT';
const WS_SEND = 'WS:SEND';
const WS_CLOSE = 'WS_CLOSE';
const WS_RECONNECT = 'WS:RECONNECT';

const GO_ONLINE = 'GO_ONLINE';
const GO_OFFLINE = 'GO_OFFLINE';

const NOTIFY = 'NOTIFY';

export {
  ESTABLISH_CONNECTION,

  ADD_MESSAGES,
  SEND_MESSAGE,

  SAVE_USERNAME,
  LOAD_USERNAME,
  SET_USERNAME,

  LS_SET,
  LS_GET,
  LS_CLEAR,

  WS_CONNECT,
  WS_SEND,
  WS_CLOSE,
  WS_RECONNECT,

  GO_ONLINE,
  GO_OFFLINE,

  NOTIFY
};
